name: Updatecli
on:
  # Allow to manually trigger Updatecli
  workflow_dispatch:
  # Trigger Updatecli on main branch changes
  # To rebase existing PR
  push:
    branches: [main]
  # Trigger Updatecli pullrequest to test potential changes
  pull_request:
    branches: [main]
  # Periodically checks update
  schedule:
    # Run every hour
    - cron: "0 * * * *"

jobs:
  updatecli:
    name: Run Updatecli
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@719e3592d124cbf826da704cbe557e1221dd4bba # v2.94.0

      - name: Run Updatecli (dryrun)
        if: github.ref != 'refs/heads/main'
        env:
          # The GitHub token is the only secrets we can use from pullrequest
          # We use it in read only mode to test that the Updatecli pipeline can still be executed
          UPDATECLI_GITHUB_USERNAME: ${{ secrets.GITHUB_TOKEN }}
          UPDATECLI_GITHUB_OWNER: ${{ github.repository_owner }}
        run: "updatecli compose diff --file updatecli/updatecli-compose.yaml"

      - name: Run Updatecli
        if: github.ref == 'refs/heads/main'
        env:
          UPDATECLI_GITHUB_APP_CLIENT_ID: ${{ secrets.APP_ID }}
          UPDATECLI_GITHUB_APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          UPDATECLI_GITHUB_APP_INSTALLATION_ID: "${{ secrets.APP_INSTALLATION_ID }}"
        run: "updatecli compose apply --file updatecli/updatecli-compose.yaml"
